AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys Nubeva TLS Decrypt & Open Source Tools in an existing VPC
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Nubeva configuration
      Parameters:
        - APIKey
        - molochInstall
        - ntopInstall
        - wiresharkInstall
    - Label:
        default: Network configuration
      Parameters:
        - VPCID
        - PrivateSubnet1ID
        - PrivateSubnet2ID
        - RemoteAccessCIDR
    - Label:
        default: Autoscaling group configuration
      Parameters:
      - KeyPairName
      - NodeInstanceType
      - NumberOfNodes
      - MaximumNodes
    - Label:
        default: AWS Quick Start configuration
      Parameters:
      - QSS3BucketName
      - QSS3KeyPrefix
    ParameterLabels:
      molochInstall:
        default: Install Moloch ASG
      ntopInstall:
        default: Install ntop ASG
      wiresharkInstall:
        default: Install Wireshark ASG
      KeyPairName:
        default: SSH key name
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      RemoteAccessCIDR:
        default: Allowed external access CIDR
      NodeInstanceType:
        default: Nodes instance type
      NumberOfNodes:
        default: Number of nodes
      MaximumNodes:
        default: Maximum number of nodes per tool
      PrivateSubnet1ID:
        default: Private subnet 1 ID
      PrivateSubnet2ID:
        default: Private subnet 2 ID
      VPCID:
        default: VPC ID
      APIKey:
        default: Nubeva Token

Parameters:
  molochInstall:    
    Default: true
    AllowedValues:
    - true
    - false
    Description: Installs Moloch Auto Scaling Group.
    Type: String
  ntopInstall:    
    Default: true
    AllowedValues:
    - true
    - false
    Description: Installs ntop Auto Scaling Group.
    Type: String
  wiresharkInstall:
    Default: true
    AllowedValues:
    - true
    - false
    Description: Installs ntop Auto Scaling Group.
    Type: String
  KeyPairName:
    Description: The name of an existing public/private key pair, which allows you
      to securely connect to your instance after it launches
    Type: AWS::EC2::KeyPair::KeyName
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description: S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: quickstart-eks-newrelic-infrastructure/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  RemoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: The CIDR IP range that is permitted to access the instances. We recommend that you set this value to a trusted IP range.
    Type: String
  NodeInstanceType:
    Default: t3.xlarge
    AllowedValues:
    - t3.large
    - t3.xlarge
    - t3.2xlarge
    - m5.large
    - m5.xlarge
    - m5.2xlarge
    - m5.4xlarge
    - m5.12xlarge
    - m5.24xlarge
    - c5.large
    - c5.xlarge
    - c5.2xlarge
    - c5.4xlarge
    - c5.9xlarge
    - c5.18xlarge
    - i3.large
    - i3.xlarge
    - i3.2xlarge
    - i3.4xlarge
    - i3.8xlarge
    - i3.16xlarge
    - r5.large
    - r5.xlarge
    - r5.2xlarge
    - r5.4xlarge
    - r5.12xlarge
    - r5.24xlarge
    ConstraintDescription: Must be a valid EC2 instance type.
    Description: The type of EC2 instance for the node instances.
    Type: String
  NumberOfNodes:
    Default: 2
    Description: The number of Amazon EKS node instances. The default is one for each of the three Availability Zones.
    Type: Number
  MaximumNodes:
    Default: 6
    Description: The maximum number of EC2 instance nodes in the each Tool Autoscaling Group.
    Type: String
  APIKey:
    Description: "The Token for your Prisms account"
    Type: String
  VPCID:
    Type: "AWS::EC2::VPC::Id"
    Description: The ID of your existing VPC (e.g., vpc-0343606e)
  PrivateSubnet1ID:
    Type: "AWS::EC2::Subnet::Id"
    Description: The ID of the private subnet in Availability Zone 1 in your existing VPC (e.g., subnet-fe9a8b32)
  PrivateSubnet2ID:
    Type: "AWS::EC2::Subnet::Id"
    Description: The ID of the private subnet in Availability Zone 2 in your existing VPC (e.g., subnet-be8b01ea)

Conditions:
  molochInstallTrue: !Equals
    - !Ref molochInstall
    - 'true'
  ntopInstallTrue: !Equals
    - !Ref ntopInstall
    - 'true'
  wiresharkInstallTrue: !Equals
    - !Ref wiresharkInstall
    - 'true'
    
Resources:
  ntopStack:
    Condition: ntopInstallTrue
    Type: AWS::CloudFormation::Stack
    Properties:
      #TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-amazon-eks/templates/amazon-eks.template.yaml'
      TemplateURL: !Sub 'https://nubevalabs.s3.amazonaws.com/nubeva-ntop.template.yaml'
      Parameters:
        KeyPairName: !Ref KeyPairName
        #QSS3BucketName: !Ref QSS3BucketName
        #QSS3KeyPrefix: !Ref QSS3KeyPrefix
        PrivateSubnet1ID: !Ref PrivateSubnet1ID
        PrivateSubnet2ID: !Ref PrivateSubnet2ID
        NumberOfNodes: !Ref NumberOfNodes
        MaximumNodes: !Ref MaximumNodes
        NodeInstanceType: !Ref NodeInstanceType
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        VPCID: !Ref VPCID
        APIKey: !Ref APIKey
  molochStack:
    Condition: molochInstallTrue
    Type: AWS::CloudFormation::Stack
    Properties:
      #TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-amazon-eks/templates/amazon-eks.template.yaml'
      TemplateURL: !Sub 'https://nubevalabs.s3.amazonaws.com/nubeva-moloch.template.yaml'
      Parameters:
        KeyPairName: !Ref KeyPairName
        #QSS3BucketName: !Ref QSS3BucketName
        #QSS3KeyPrefix: !Ref QSS3KeyPrefix
        PrivateSubnet1ID: !Ref PrivateSubnet1ID
        PrivateSubnet2ID: !Ref PrivateSubnet2ID
        NumberOfNodes: !Ref NumberOfNodes
        MaximumNodes: !Ref MaximumNodes
        NodeInstanceType: !Ref NodeInstanceType
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        VPCID: !Ref VPCID
        APIKey: !Ref APIKey
  wiresharkStack:
    Condition: wiresharkInstallTrue
    Type: AWS::CloudFormation::Stack
    Properties:
      #TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-amazon-eks/templates/amazon-eks.template.yaml'
      TemplateURL: !Sub 'https://nubevalabs.s3.amazonaws.com/nubeva-wireshark.template.yaml'
      Parameters:
        KeyPairName: !Ref KeyPairName
        #QSS3BucketName: !Ref QSS3BucketName
        #QSS3KeyPrefix: !Ref QSS3KeyPrefix
        PrivateSubnet1ID: !Ref PrivateSubnet1ID
        PrivateSubnet2ID: !Ref PrivateSubnet2ID
        NumberOfNodes: !Ref NumberOfNodes
        MaximumNodes: !Ref MaximumNodes
        NodeInstanceType: !Ref NodeInstanceType
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        VPCID: !Ref VPCID
        APIKey: !Ref APIKey
#Outputs:
