apiVersion: apps/v1
kind: Deployment
metadata:
  name: tlsgen
  labels:
    app: tlsgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tlsgen
  template:
    metadata:
      labels:
        app: tlsgen
    spec:
      containers:
      - name: tlsgen
        image: ejfree/tlsgenerator:update
