AWSTemplateFormatVersion: '2010-09-09'
Description: 'Windows with Wireshark'

Parameters:
  APIKey:
    Description: "The Token for your Prisms account"
    Type: String
  VPCid:
    Description: 'VPC ID'
    Type: "AWS::EC2::VPC::Id"
  Subnetid:
    Description: 'Subnet ID'
    Type: "AWS::EC2::Subnet::Id"
  CIDR:
    Type: String
    Description: The CIDR notation of address to access the clients
    Default: '0.0.0.0/0'
  KeyName:
    Description: 'Optional key pair of the ec2-user to establish a SSH connection to the EC2 instance.'
    Type: "AWS::EC2::KeyPair::KeyName"
  CustomAMI:
    Description: AMI ID -- Change if custom AMI is desired
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  InstanceType:
    Description: 'The instance type for the EC2 instance.'
    Type: String
    Default: 't3.medium'
  DesiredInstances:
    Description: 'The number of EC2 instances'
    Type: Number
    Default: 1

Conditions:
  HasKeyName: !Not [!Equals [!Ref KeyName, '']]


Resources:
  # Security Groups
  # The Security Group placed on the clients themselves
  ClientSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Client Security Group
      VpcId: !Ref 'VPCid'
  # Inbound- allow ssh
  SecurityGroupSSHinbound:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref "ClientSecurityGroup"
      IpProtocol: tcp
      FromPort: '3389'
      ToPort: '3389'
      CidrIp: !Ref "CIDR"
  # Outbound- allow all
  ClientSecurityGroupOutbound:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref "ClientSecurityGroup"
      CidrIp: 0.0.0.0/0
      IpProtocol: "-1"
      FromPort: '-1'
      ToPort: '-1'

  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: '/'
      Roles:
      - !Ref IAMRole

  IAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'ec2.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      Path: '/'
      Policies:
      - PolicyName: asg
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - 'autoscaling:DescribeAutoScalingGroups'
            - 'autoscaling:DescribeAutoScalingInstances'
            - 'ec2:DescribeInstances'
            Resource:
            - '*'


  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      # AvailabilityZones: !Ref AvailabilityZones
      VPCZoneIdentifier:
      - Ref: Subnetid
      LaunchConfigurationName: !Ref LaunchConfiguration
      MinSize: 0
      MaxSize: 200
      DesiredCapacity: !Ref DesiredInstances
      MetricsCollection:
      - Granularity: 1Minute
        Metrics:
        - GroupInServiceInstances
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}
        PropagateAtLaunch: 'true'
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: !Ref DesiredInstances
        MaxBatchSize: '1'
        PauseTime: PT10M
        SuspendProcesses:
        - AlarmNotification
        WaitOnResourceSignals: 'true'

  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
        # List the configSets and the config keys they contain:
          Install:
            - "installPrismsAgent"
        # Config key: installServices
#        installServices:
#          packages:
#            yum:
#              docker: []
#              git: []
#          services:
#            sysvinit:
#              docker:
#                enabled: true
#                ensureRunning: true
       #  Config key: installPrismsAgent
        installPrismsAgent:
          commands:
            01_download_and_install:
              command: "echo \"Debug1\""
#                !Sub |
#                  docker run -v /:/host -v /var/run/docker.sock:/var/run/docker.sock --privileged --name nubeva-agent -d --restart=on-failure --net=host nubeva/nuagent --accept-eula --nutoken ${APIKey}
#            02_installTools:
#              command: "git clone https://github.com/nubevalabs/NubevaTools.git /opt/NubevaTools"

    Properties:
#      ImageId: !Ref CustomAMI
      ImageId: "ami-0a9ca0496f746e6e0"
      InstanceType: !Ref InstanceType
      SecurityGroups:
      - !Ref "ClientSecurityGroup"
      IamInstanceProfile: !Ref InstanceProfile
      AssociatePublicIpAddress: "true"
      KeyName:
        Ref: KeyName
      UserData:
        Fn::Base64: !Sub |
          <script>
          cfn-init -v --region ${AWS::Region} --stack ${AWS::StackName} --resource LaunchConfiguration --configsets Install
          cfn-signal -e %errorlevel% --region ${AWS::Region} --stack ${AWS::StackName} --resource AutoScalingGroup
          </script>
          <powershell>
          $Path = $env:TEMP; $Installer = "Wireshark-win64-3.0.2.exe"; Invoke-WebRequest "https://1.na.dl.wireshark.org/win64/Wireshark-win64-3.0.2.exe" -OutFile $Path\$Installer; Start-Process -FilePath $Path\$Installer -Args “/S /desktopicon=yes" -Verb RunAs -Wait; Remove-Item $Path\$Installer
          </powershell>

#          powershell -Command "(New-Object Net.WebClient).DownloadFile('https://s3.amazonaws.com/amazoncloudwatch-agent/windows/amd64/latest/amazon-cloudwatch-agent.msi','C:\Downloads\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent.msi')"
