KeyPairName: nudemo
PrivateSubnet1ID: subnet-0b21f8a80e117f903
PrivateSubnet2ID: subnet-0ed88a6ff7598f025
VPCID: vpc-09106387bb70b216d
APIKey: avnujtoj_D1don13jxtUQoGovougnelugODOAdlOdxOu7jVx9jDq5Vx7goL1QqVgl9AxulunG
ToolPassword: BANzai99
